spring.application.name=backend
server.port=8081

# ===============================

# DATABASE (PostgreSQL)

# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/health_record
spring.datasource.username=postgres
spring.datasource.password=giang2004
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================

# JPA / HIBERNATE

# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ===============================

# FILE UPLOAD

# ===============================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================

# DEVTOOLS (HOT RELOAD)

# ===============================

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# ===============================

# LOGGING

# ===============================

logging.level.org.springframework.web=debug
logging.level.root=info

# ===============================

# JWT SECURITY

# ===============================

application.security.jwt.secret-key=v8kzWqYIMRwfLfrKRKQhdOX0bbhrNy+r+iAJBWlZJNE=

# ===============================

# CLOUDINARY

# ===============================

cloudinary.cloud_name=dtl1676rh
cloudinary.api_key=871628432578491
cloudinary.api_secret=UG34h03QJhsfp5YggfbtgytuBno

# ===============================

# EMAIL (GMAIL SMTP)

# ===============================


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=giangvthe182222@fpt.edu.vn
spring.mail.password=iqlbuhdyltwclgue



app.mail.enabled=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
